language: objective-c
# xcode_workspace: Instarant.xcworkspace
# osx_image: xcode8.3
# xcode_sdk: iphonesimulator10.3

script:
    xctool -workspace Instarant.xcworkspace -scheme Instarant build test -sdk iphonesimulator