language: objective-c
# xcode_workspace: Instarant.xcworkspace
# xcode_project: Instarant.xcodeproj
xcode_scheme: Instarant
osx_image: xcode8.3
xcode_sdk: iphonesimulator10.3

# script:
    # - xctool -workspace Instarant.xcworkspace -scheme Instarant build -sdk iphonesimulator
#     
#     
#     
# script:
#   - xctool -workspace Instarant.xcworkspace -scheme Instarant -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  # - xctool test -workspace Instarant.xcworkspace -scheme Instarant -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

# script:
#     - xcodebuild -workspace Instarant.xcworkspace -scheme Instarant test



script:
    - xcodebuild clean build -sdk iphonesimulator -workspace Instarant.xcworkspace -scheme Instarant CODE_SIGNING_REQUIRED=NO